name: Variables and Secrets

on:
  workflow_dispatch:

env:
  COURSE: DevOps

jobs:

  variables-job:

    runs-on: ubuntu-latest

    steps:

      - name: Print variable
        run: |
          echo "Course: $COURSE"
          echo "App: ${{ vars.APP_NAME }}"

      - name: Print secret
        run: |
          echo "Secret loaded successfully"
